version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  
  db:
    container_name: database
    build:
      context: database/
      dockerfile: Dockerfile
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventory

volumes:
  postgres_data: